# バージョン2記法で記述する
version: '2'

# 起動するコンテナを定義する
services:

  # Jettyコンテナ
  jetty:
    # Dockerfileからビルドするのではなく、Docker Hubの公式イメージを使う
    # サイズが小さいAlpineベースのイメージを使う
    image: jetty:9.4.1-alpine

    # コンテナ内のポートをホストに公開する
    # 書式 "HOST:CONTAINER"
    ports:
      # Jettyのポートを同じ番号でホストに公開する
      - "8080:8080"
    volumes:
      # Jettyのデプロイフォルダーに、GradleがWARを生成する先をマウントする
      # foo.war には http://localhost:8080/foo でアクセスできるようになる
      - ./build/libs:/var/lib/jetty/webapps
    links:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: testuser
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-initdb
    ports:
      - 3306:3306